apiVersion: apps/v1
kind: Deployment
metadata:
  name: catd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catd
  template:
    metadata:
      labels:
        app: catd
    spec:
      containers:
      - image: okteto.dev/catd:latest
        name: catd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "0986d4a1-aa27-4477-a9ff-6e169cd8449c"
        - name: Vless_Path
          value: "/bkmfsy"
        - name: Vmess_UUID
          value: "0986d4a1-aa27-4477-a9ff-6e169cd8449c"
        - name: Vmess_Path
          value: "/gdy6trsf"
        - name: Share_Path
          value: "/Share534"
