apiVersion: apps/v1
kind: Deployment
metadata:
  name: quait
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quait
  template:
    metadata:
      labels:
        app: quait
    spec:
      containers:
      - image: okteto.dev/quait:latest
        name: quait
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.lenskart.com"
        - name: Vless_UUID
          value: "0c1f1c18-fe56-48a1-8df6-5980918d073b"
        - name: Vless_Path
          value: "/giyreas"
        - name: Vmess_UUID
          value: "0c1f1c18-fe56-48a1-8df6-5980918d073b"
        - name: Vmess_Path
          value: "/BNKDS2GU"
        - name: Share_Path
          value: "/Share764"
