apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrecp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrecp
  template:
    metadata:
      labels:
        app: xrecp
    spec:
      containers:
      - image: okteto.dev/xrecp:latest
        name: xrecp
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "9b069e66-211a-48d0-8d6f-6a7779a8b296"
        - name: Vless_Path
          value: "/gy6we34"
        - name: Vmess_UUID
          value: "9b069e66-211a-48d0-8d6f-6a7779a8b296"
        - name: Vmess_Path
          value: "/xiezrku"
        - name: Share_Path
          value: "/Share076"
