apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwecikt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rwecikt
  template:
    metadata:
      labels:
        app: rwecikt
    spec:
      containers:
      - image: okteto.dev/rwecikt:latest
        name: rwecikt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "93a6c607-b5ad-4cf1-bfca-d4733aa81fa4"
        - name: Vless_Path
          value: "/s45twesd"
        - name: Vmess_UUID
          value: "93a6c607-b5ad-4cf1-bfca-d4733aa81fa4"
        - name: Vmess_Path
          value: "/wkfsjie"
        - name: Share_Path
          value: "/Share433"
